### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by lucasliet** [lucasliet/ReciclaMais#1]
- [x] Adicionar tipos de lixo e endereço na descrição dos locais
- [x]  Corrigir bug da array no JavaScript que ele adiciona objetos fora da array duplicando a array em cada adição
- [x]  Discutir como fazer o campo de **Sugestões**
- [x]  Adicionar Vídeo de instrução na área "**Como Separar**"
- [x]  Adicionar locais ao **maphub**

**Comment by lucasliet** [comment]
- [ ] Criar **Logo**
- [x] Separar campo de **Rua**, **Número** e **CEP** em endereço na página de **Sugestões**
- [ ] Melhorar **responsividade** do Layout
- [ ] Gravar **vídeo** para o Como Separar @EloYoshida 
- [ ] **Separar página** com lista de locais sugeridos @lucasliet 
- [ ] Criar interface **Mobile**

**Comment by lucasliet** [comment]
### Nossa página ja ta **online!** 

> http://bit.do/reciclamais

![QR Code](https://user-images.githubusercontent.com/49222261/67966528-c94da380-fbe2-11e9-9afb-92504f748722.png)
